# Generated by Django 5.2.9 on 2025-12-05 10:11

import relecloud.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, JPEG, PNG, WEBP. Tamaño máximo: 5MB', null=True, upload_to='destinations/', validators=[relecloud.validators.validate_image_extension, relecloud.validators.validate_image_size]),
        ),
    ]
