# Generated by Django 5.2.9 on 2025-12-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_destination_image'),
        ('relecloud', '0002_review'),
    ]

    operations = [
    ]
