# Generated by Django 5.2.9 on 2025-12-05 20:00

import relecloud.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Formato: JPG, PNG o WEBP. Máximo 5MB. Dimensiones: 300x300 a 2000x2000 píxeles', null=True, upload_to='destinations/', validators=[relecloud.validators.validate_image_extension, relecloud.validators.validate_image_size, relecloud.validators.validate_image_dimensions]),
        ),
    ]
